services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: autotest-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}"
    volumes:
      - autotest_postgres_data:/var/lib/postgresql

volumes:
  autotest_postgres_data: